dist: xenial
language: java
services:
- docker
env:
- CHANGE_MINIKUBE_NONE_USER=true
before_script:
- unset _JAVA_OPTIONS
- cd finish
- chmod +x ../scripts/travisTest.sh
script: 
- sudo mount --make-rshared /
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
- chmod +x kubectl
- sudo ln -s $(pwd)/kubectl /usr/local/bin/kubectl
- wget https://storage.googleapis.com/minikube/releases/v0.30.0/minikube-linux-amd64 -q -O minikube
- chmod +x minikube
- sudo ln -s $(pwd)/minikube /usr/local/bin/minikube
- sudo minikube start --vm-driver=none --bootstrapper=kubeadm --kubernetes-version=v1.12.0 
- minikube update-context 
- sudo apt-get install -y --upgrade util-linux socat
- wget https://get.helm.sh/helm-v3.1.2-linux-amd64.tar.gz -q -O helm.tar.gz
- tar -zxf helm.tar.gz
- chmod +x ./linux-amd64/helm
- sudo ln -s $(pwd)/linux-amd64/helm /usr/local/bin/helm
- ../scripts/travisTest.sh
after_script:
- docker images
- if [[ "$TRAVIS_TEST_RESULT" == "0" ]]; then RESULT="passed"; else RESULT="failed"; fi
- echo -e "\033[1;34m result:\033[0m\033[1;36m $RESULT \033[0m \n"
notifications:
  slack:
    template:
    - 'Build: <%{build_url}| %{build_number}> | Commit (<%{compare_url}|%{commit}>):
      %{commit_message}'
    - 'Repo@Branch: %{repository_slug}@%{branch}'
    - 'Author: %{author}'
    - 'Summary: %{result} in %{duration}'
    rooms:
      secure: e6hb1sp1y+ZLkwgK7cR++FLrRyM++mB1R+4VM3CI/qYbdN0A+n5swNzSSfb4FUP/n6i/3cbAN+lhJa5+9goUNg6pacjht42gCSchUkW+FPUS+LbKR2MKCBVBBbOrMa+5ZL3/0Yl+/xVzfLRFJVUc8TGMpEvKwnoPkiJhz+uGYDHLKKnRT6zsaSsJzDDCuQihBgKvF8lKooYZHUczglBTN8bqWDhoA7ZFxOf1kf8TBdE3P+BzcbOb+f22uO20sqAPcLkDbNFrJ3NjgZf+w3tZmIH4YNOje4dsWzXSagHelXO8+VGwuH0AIHglIJfp0LpD03ZMU+3dblVgtcDv/56URtPIOQ2pjUjheGtxX2khzP52WIvQtmaYZnEr/mSOY4WRc60z9Kw2GMiGEnD42CjYmbbH4cbXeacgTCPaxMKytdpydIkYFEG5O5sEli4/+tUMjRS1+s23dIqrmmrO53GSbO0RJAVZZqXIaOuqP3BVKksWiq7wN5ZH3jvlvz3/1SuOLOWndMfZx/YE6BCmzfKRGkXHkdMXbdw/wQTwvLDQkztgMkTaZlt47nI7yssZIs9QEvJB0yCcMxweF4dVbkHA+6z/Txam0ETVcZ39gRd2SPHOCgyRKlm7mNpkqY72w08MR8ozEdgF4RzG9MLBHbpPn/QtRzHvdEz5zRBhUa2jiHc=
    on_success: never
    on_failure: always
branches:
  only:
  - master
  - qa
